// utils/icons.ts
import {
  faWrench, faTrash, faCar, faUser, faCoins, faShield,
  faChevronRight, faChevronUp, faChevronDown, faCheck,
  faStar, faBolt, faGear, faLocationDot, faGun, faMedkit,
  faSkull, faHouse, faPhone, faEnvelope, faKey, faLock,
  faUnlock, faBan, faFlag, faHandcuffs, faHammer, faFireFlameCurved,
  faBoxes, faArrowRight, faCircleInfo, faTriangleExclamation,
  faCircleXmark, faCircleCheck, faPen, faEye, faEyeSlash,
  faRotate, faClock, faCalendar, faIdCard, faDollarSign,
  faMoneyBill, faHandshake, faFileLines, faMap, faBars,
  faExplosion, faMotorcycle, faTruck, faHelicopter, faPlaneDeparture,
  faVestPatches, faUserTie, faUserSecret, faMicroscope,
  faDatabase, faCodeBranch, faTerminal, faWifi, faServer,
} from '@fortawesome/free-solid-svg-icons'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'

const iconMap: Record<string, IconDefinition> = {
  wrench:       faWrench,
  trash:        faTrash,
  car:          faCar,
  user:         faUser,
  coins:        faCoins,
  shield:       faShield,
  'chevron-right': faChevronRight,
  'chevron-up':    faChevronUp,
  'chevron-down':  faChevronDown,
  check:        faCheck,
  star:         faStar,
  bolt:         faBolt,
  gear:         faGear,
  location:     faLocationDot,
  gun:          faGun,
  medkit:       faMedkit,
  skull:        faSkull,
  house:        faHouse,
  phone:        faPhone,
  envelope:     faEnvelope,
  key:          faKey,
  lock:         faLock,
  unlock:       faUnlock,
  ban:          faBan,
  flag:         faFlag,
  handcuffs:    faHandcuffs,
  hammer:       faHammer,
  fire:         faFireFlameCurved,
  boxes:        faBoxes,
  arrow:        faArrowRight,
  info:         faCircleInfo,
  warning:      faTriangleExclamation,
  error:        faCircleXmark,
  success:      faCircleCheck,
  pen:          faPen,
  eye:          faEye,
  'eye-slash':  faEyeSlash,
  rotate:       faRotate,
  clock:        faClock,
  calendar:     faCalendar,
  id:           faIdCard,
  dollar:       faDollarSign,
  money:        faMoneyBill,
  handshake:    faHandshake,
  file:         faFileLines,
  map:          faMap,
  bars:         faBars,
  explosion:    faExplosion,
  motorcycle:   faMotorcycle,
  truck:        faTruck,
  helicopter:   faHelicopter,
  plane:        faPlaneDeparture,
  vest:         faVestPatches,
  tie:          faUserTie,
  secret:       faUserSecret,
  microscope:   faMicroscope,
  database:     faDatabase,
  code:         faCodeBranch,
  terminal:     faTerminal,
  wifi:         faWifi,
  server:       faServer,
}

export function getIcon(name?: string): IconDefinition | null {
  if (!name) return null
  return iconMap[name] ?? null
}
